apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: quicklabs5
  labels:
    name: redis-config
    app: redis
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
