---
apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: quicklabs1
spec:
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-claim
  containers:
    - name: logger
      image: library/nginx:alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/www/nginx"
          name: log-volume
      livenessProbe:
        tcpSocket:
          port: 80
        failureThreshold: 3
        initialDelaySeconds: 30
        timeoutSeconds: 5
        periodSeconds: 10