---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
  namespace: quicklabs1
  labels:
    name: log-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi