---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-dind-878516
  namespace: quicklabs10
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: engine-x
  - command:
    - sleep
    - "3600"
    image: ubuntu
    imagePullPolicy: Always
    name: agent-x
  - image: kodekloud/event-simulator
    imagePullPolicy: Always
    name: log-x
    volumeMounts:
      - mountPath: /opt/
        name: warn-logs
  restartPolicy: Always
  volumes:
    - name: warn-logs
      emptyDir: {}