---
apiVersion: v1
kind: Pod
metadata:
  namespace: quicklabs3
  name: time-check
  labels:
    name: time-check
spec:
  containers:
    - name: time-check
      imagePullPolicy: Always
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date); sleep $TIME_FREQ > /opt/time/time-check.log;done"]
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
      env:
        - name: TIME_FREQ
          value: "10"
      volumeMounts:
        - mountPath: /opt/time
          name: time-check-vol
  restartPolicy: OnFailure
  volumes:
    - name: time-check-vol
      emptyDir: {}
