---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: quicklabs9
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30093
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30508
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: NodePort